---
baseURL: "/"  # this should be updated to https://carvel.dev once it's deployed
disablePathToLower: true
languageCode: en-us
DefaultContentLanguage: "en"
title: "Carvel"
theme: "carvel"
frontmatter:
  date: [":filename", ":default"]
params:
  products: [ytt, kbld, kapp, imgpkg, kapp-controller, vendir]
  ytt:
    name: ytt
    root_link: /ytt/
    latest_docs_link: /ytt/docs/latest/
    github_url: https://github.com/vmware-tanzu/carvel-ytt
    search: false
    search_index_name: index_name
    search_api_key: api_key
    versioning: false
    version_latest: latest
    versions:
      - latest
  kbld:
    name: kbld
    root_link: /kbld/
    latest_docs_link: /kbld/docs/latest/
    github_url: https://github.com/vmware-tanzu/carvel-kbld
    search: false
    search_index_name: index_name
    search_api_key: api_key
    versioning: false
    version_latest: latest
    versions:
      - latest
  kapp:
    name: kapp
    root_link: /kapp/
    latest_docs_link: /kapp/docs/latest/
    github_url: https://github.com/vmware-tanzu/carvel-kapp
    search: false
    search_index_name: index_name
    search_api_key: api_key
    versioning: false
    version_latest: latest
    versions:
      - latest
  imgpkg:
    name: imgpkg
    root_link: https://github.com/vmware-tanzu/carvel-imgpkg # not enabled yet: /imgpkg/
    latest_docs_link: /imgpkg/docs/latest/
    github_url: https://github.com/vmware-tanzu/carvel-imgpkg
    search: false
    search_index_name: index_name
    search_api_key: api_key
    versioning: false
    version_latest: latest
    versions:
      - latest
  kapp-controller:
    name: kapp-controller
    root_link: https://github.com/vmware-tanzu/carvel-kapp-controller # not enabled yet: /kapp-controller/
    latest_docs_link: /kapp-controller/docs/latest/
    github_url: https://github.com/vmware-tanzu/carvel-kapp-controller
    search: false
    search_index_name: index_name
    search_api_key: api_key
    versioning: false
    version_latest: latest
    versions:
      - latest
  vendir:
    name: vendir
    root_link: /vendir/
    latest_docs_link: /vendir/docs/latest/
    github_url: https://github.com/vmware-tanzu/carvel-vendir
    search: false
    search_index_name: index_name
    search_api_key: api_key
    versioning: false
    version_latest: latest
    versions:
      - latest
  links:
    twitter_url: https://twitter.com/carvel_dev
    github_url: https://github.com/vmware-tanzu/carvel
    slack_url: https://kubernetes.slack.com/archives/CH8KCCKA5
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 4
permalinks:
  tags: "/blog/tags/:slug"
