---
baseURL: "/"  # this should be updated to https://carvel.dev once it's deployed
disablePathToLower: true
languageCode: en-us
DefaultContentLanguage: "en"
title: "Carvel"
theme: "carvel"
frontmatter:
  date: [":filename", ":default"]
params:
  products: [ytt, kbld, kapp]
  ytt:
    root_link: /ytt/
    latest_docs_link: /ytt/docs/v0.30.0/
    github_url: https://github.com/vmware-tanzu/carvel-ytt
  kbld:
    root_link: /kbld/
    latest_docs_link: /kbld/docs/v0.27.0/
    github_url: https://github.com/vmware-tanzu/carvel-kbld
  kapp:
    root_link: /kapp/
    latest_docs_link: /kapp/docs/v0.34.0/
    github_url: https://github.com/vmware-tanzu/carvel-kapp
  next_meeting_date: 2020-11-05
  ytt_versioning: false
  ytt_search: false
  ytt_search_index_name: index_name
  ytt_search_api_key: api_key
  ytt_latest: v0.30.0
  ytt_versions:
    - v0.30.0
  kbld_versioning: false
  kbld_search: false
  kbld_search_index_name: index_name
  kbld_search_api_key: api_key
  kbld_latest: v0.27.0
  kbld_versions:
    - v0.27.0
  kapp_versioning: false
  kapp_search: false
  kapp_search_index_name: index_name
  kapp_search_api_key: api_key
  kapp_latest: v0.34.0
  kapp_versions:
    - v0.34.0
  links:
    twitter_url: https://twitter.com/carvel_dev
    github_url: https://github.com/vmware-tanzu/carvel
    slack_url: https://kubernetes.slack.com/archives/CH8KCCKA5
  vm_logo: vm-logo.png
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 4
