[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.78.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.78.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.78.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.78.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://get-kapp.io/*"
  to = "https://carvel.dev/kapp"
  status = 302
  force = true

[[redirects]]
  from = "https://www.get-kapp.io/*"
  to = "https://carvel.dev/kapp"
  status = 302
  force = true

[[redirects]]
  from = "https://get-kbld.io/*"
  to = "https://carvel.dev/kbld"
  status = 302
  force = true

[[redirects]]
  from = "https://www.get-kbld.io/*"
  to = "https://carvel.dev/kbld"
  status = 302
  force = true

[[redirects]]
  from = "/install.sh"
  to = "https://raw.githubusercontent.com/vmware-tanzu/carvel.dev/develop/static/install.sh"
  status = 302
  force = true