baseURL: https://carvel.dev
disablePathToLower: true
languageCode: en-us
DefaultContentLanguage: en
title: Carvel
theme: carvel
frontmatter:
  date:
  - :filename
  - :default
params:
  products:
  - kapp-controller
  - ytt
  - kapp
  - kbld
  - imgpkg
  - vendir
  search:
    app_id: BSVMS0V37R
  ytt:
    name: ytt
    root_link: /ytt/
    latest_docs_link: /ytt/docs/v0.40.0/
    github_url: https://github.com/vmware-tanzu/carvel-ytt
    search: true
    search_index_name: carvel-ytt
    search_api_key: a38560864c2e9128ae57d5734df438ff
    versioning: true
    version_latest: v0.40.0
    versions:
    - develop
    - v0.40.0
    - v0.39.0
    - v0.38.0
  kbld:
    name: kbld
    short_name: kbld
    root_link: /kbld/
    latest_docs_link: /kbld/docs/v0.32.0/
    github_url: https://github.com/vmware-tanzu/carvel-kbld
    search: true
    search_index_name: carvel-kbld
    search_api_key: a38560864c2e9128ae57d5734df438ff
    versioning: true
    version_latest: v0.32.0
    versions:
    - develop
    - v0.32.0
  kapp:
    name: kapp
    short_name: kapp
    root_link: /kapp/
    latest_docs_link: /kapp/docs/v0.46.0/
    github_url: https://github.com/vmware-tanzu/carvel-kapp
    search: true
    search_index_name: carvel-kapp
    search_api_key: a38560864c2e9128ae57d5734df438ff
    versioning: true
    version_latest: v0.46.0
    versions:
    - develop
    - v0.46.0
    - v0.45.0
    - v0.44.0
  imgpkg:
    name: imgpkg
    short_name: imgpkg
    root_link: /imgpkg/
    latest_docs_link: /imgpkg/docs/v0.25.0/
    github_url: https://github.com/vmware-tanzu/carvel-imgpkg
    search: true
    search_index_name: carvel-imgpkg
    search_api_key: a38560864c2e9128ae57d5734df438ff
    versioning: true
    version_latest: v0.25.0
    versions:
    - develop
    - v0.25.0
    - v0.24.0
  kapp-controller:
    name: kapp-controller
    short_name: kc
    root_link: /kapp-controller/
    latest_docs_link: /kapp-controller/docs/v0.32.0/
    github_url: https://github.com/vmware-tanzu/carvel-kapp-controller
    search: true
    search_index_name: carvel-kapp-controller
    search_api_key: a38560864c2e9128ae57d5734df438ff
    versioning: true
    version_latest: v0.32.0
    versions:
    - develop
    - v0.32.0
    - v0.31.0
  vendir:
    name: vendir
    short_name: vendir
    root_link: /vendir/
    latest_docs_link: /vendir/docs/v0.24.0/
    github_url: https://github.com/vmware-tanzu/carvel-vendir
    search: true
    search_index_name: carvel-vendir
    search_api_key: a38560864c2e9128ae57d5734df438ff
    versioning: true
    version_latest: v0.24.0
    versions:
    - develop
    - v0.24.0
  links:
    twitter_url: https://twitter.com/carvel_dev
    github_url: https://github.com/vmware-tanzu/carvel
    slack_url: https://kubernetes.slack.com/archives/CH8KCCKA5
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 4
permalinks:
  tags: /blog/tags/:slug
